"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["secure.opencon2015.org"]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'spreadsheet',
    'rating',
    'application',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ADMINS = (
    ("Juraj Pelikan", "opencon@webscale.sk"),
    ("Jan Gondol", "gondol@gondol.sk"),
    ("Joe McArthur", "joe@righttoresearch.org"),
)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "..", "static")

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

SHEET_NAMES = {
    "applications": "applications2015",
    "users": "users2015",
}

TOKEN_NAME = "2015"
TOKEN_SCOPE = "https://spreadsheets.google.com/feeds"

EMAIL_BACKEND = 'django_mailgun.MailgunBackend'
MAILGUN_SERVER_NAME = "opencon2015.org"
MAILGUN_ACCESS_KEY = "key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
FROM_MAIL = "noreply@opencon2015.org"
WELCOME_MAIL_ENABLED = False
REVIEWER_MAIL_ENABLED = False

BASE_URL = "https://secure.opencon2015.org"

APPEND_SLASH = True

USER_FIELDS = {
    "timestamp": "Timestamp",
    "email": "E-Mail Address",
    "terminator": "Terminator",
    "organizer": "Organizing Committee",
    "enabled": "Enabled",
}

USER_INFO_FIELDS = {
    "Timestamp",
    "E-Mail Address",
    "Enabled",
    "Terminator",
    "Please verify that you attended OpenCon 2014",
    "Organizing Committee",
    "Last Name",
    "Notes",
    "First Name",
    "Time Commitment",
    "Confirm E-Mail Address",
    "Availability"
}

APPLICATION_FIELDS = {
    "timestamp": "Timestamp",
    "email": "E-Mail Address",
    "approval_level": "Approval Level",
    "final_decision": "Final Decision"
}

APPLICATION_INFO_FIELDS = [
    u"What is your primary area of interest within OpenCon\u2019s program areas?^",
    u"What is your interest in Open Access, Open Education and/or Open Data and how does it relate to your work?",
    u"If you are currently engaged in activities to advance Open Access, Open Education and/or Open Data, please describe them. If you are not currently engaged, how would you plan to get involved?",
    u"How would you use your experience at OpenCon to advance Open Access, Open Education and/or Open Data? If you attended OpenCon last year, please address how attending OpenCon again would help you build upon your work.",
    u"Are you planning to participate in any of the following events this year?^",
    u"For the events you checked, please explain how you plan to participate.",
    u"Please check all that apply to you:",
    u"How did you find out about OpenCon 2015?",
    u"Do you have any of the following skills or interests?^",
]

APPLICATION_INFO_FIELDS_PHASE2 = [
    u"First Name (Given Name)",
    u"Last Name (Family Name)",
    u"Country of Nationality^",
    u"Country of Residence^",
    u"What is your primary occupation?^",
    u"What best describes your career stage?^",
    u"Institution / Employer",
    u"Select the option below that best describes your field of study or expertise^",
    u"Organization(s) with which you are affiliated",
    u"Leadership Positions",
    u"What is your primary area of interest within OpenCon\u2019s program areas?^",
    u"What is your interest in Open Access, Open Education and/or Open Data and how does it relate to your work?",
    u"If you are currently engaged in activities to advance Open Access, Open Education and/or Open Data, please describe them. If you are not currently engaged, how would you plan to get involved?",
    u"How would you use your experience at OpenCon to advance Open Access, Open Education and/or Open Data? If you attended OpenCon last year, please address how attending OpenCon again would help you build upon your work.",
    u"Are you planning to participate in any of the following events this year?^",
    u"For the events you checked, please explain how you plan to participate.",
    u"Please check all that apply to you:",
    u"Do you have any of the following skills or interests?^",
]

    # "Timestamp",
    # "E-Mail Address",
    # "First Name (Given Name)",
    # "Please check the boxes below to acknowledge the following statements",
    # "Twitter Username (Optional)",
    # "Country of Nationality^",
    # "Institution / Employer",
    # "Would you like to apply for a travel scholarship?^",
    # "Select the option below that best describes your field of study or expertise^",
    # "City you would most likely travel to/from to get to OpenCon if accepted",
    # "Please indicate whether you would need a visa to travel to Brussels, Belgium to attend OpenCon 2015^",
    # "Three letter code for the airport you would most likely travel from to get to OpenCon if accepted",
    # "What is your specific field of study or expertise?",
    # "Organization(s) with which you are affiliated",
    # "Nickname / Preferred Name",
    # "If you DO NOT wish to be included in the following options, please opt out below",
    # "Last Name (Family Name)",
    # "Leadership Positions",
    # "Confirm E-Mail Address",
    # "If you DO NOT wish to be included in the following options, please opt out below:",
    # "Country of Residence^",
    # "In what year did you receive your most recent university degree (if any)?",
    # "What best describes your career stage?^",
    # "Gender^",
    # "What is your primary occupation?^",

try:
    from .local_settings import *
except ImportError:
    pass
